### ISSUE TITLE
does not compile on ubuntu 16.04

### ISSUE THREAD

**Issue by m2049r** [satoshinm/pill_duck#12]
$ make
  GIT     version.h
  CC      cdcacm.c
  CC      hid.c
  CC      hex_utils.c
  CC      flash.c
  CC      main.c
main.c:99:67: error: missing braces around initializer [-Werror=missing-braces]
 static struct composite_report packet_buffer[1024 / sizeof(struct composite_report)] = {0};
                                                                   ^
main.c:99:67: error: (near initialization for 'packet_buffer[0]') [-Werror=missing-braces]
cc1: all warnings being treated as errors
Makefile:49: recipe for target 'main.o' failed
make: *** [main.o] Error 1
